import os
import psycopg
from psycopg.rows import dict_row

# El Driver de Postgres
# https://pypi.org/project/psycopg/
# pip install "psycopg[binary]"

def conectar():
    url = "postgresql://postgres:admin@localhost:5432/tienda_postgres" # string de conexión (URI)
    return psycopg.connect(url, row_factory=dict_row)

def inicializar():
    with conectar() as conexion:
        conexion.execute("""
            CREATE TABLE IF NOT EXISTS productos (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre TEXT NOT NULL,
                precio NUMERIC(12, 2) NOT NULL CHECK (precio >= 0),
                stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0)
            )
        """)
        # 1_111_111_111.22 # SI
        # 111111111111.22 # NO
        
# Test
# inicializar()